Reorder filters, Add code to check if any filter options have been updated
serotracker/iit-backend pull request #134
Opened 2021-01-25 03:05 UTC by atatmaja

2021-01-26 04:03 UTC, simonarocco requested changes

2021-01-26 15:23 UTC, atatmaja commented on app/utils/get_filter_options.py
> +def get_filter_static_options():
As we discussed over the phone, this is needed because we need to semantically order all these filter fields. Resolving

2021-01-26 15:23 UTC, atatmaja commented on app/database_etl/etl_main.py
> +        if new_options != set(curr_filter_options[filter_type]):
As we discussed over the phone, this function simply validates our filter options. Resolving

2021-01-26 15:24 UTC, atatmaja commented on app/database_etl/etl_main.py
> +        for s in to_ignore:
sounds good

2021-01-27 19:09 UTC, atatmaja commented
![image](https://user-images.githubusercontent.com/21212898/106041006-41866b80-60a9-11eb-99d0-109154831e83.png)

2021-01-27 19:13 UTC, merged