Update README and CI
serotracker/iit-backend pull request #207
Opened 2021-04-30 02:06 UTC by abeljoseph

## Briefly describe the feature or bug that this PR addresses.
Update README.

## Please link the Airtable ticket associated with this PR.
https://airtable.com/tbli2lWQHAqBa6ZcI/viwSkpZmJR8D99kla/recbKtLwhee97VY07?blocks=hide

2021-05-05 15:26 UTC, atatmaja commented on README.md
> +Deployment is conducted server-side. The documentation can be found [here](https://github.com/serotracker/scripts#update_backendsh).
Can you include some documentation around how we've made the update_backend script run every 5 mins (i.e. command used to setup the cron job, how to view information about it and configure it for the future, etc)?

Also afaik you have some alerting/monitoring setup to view CI/CD results. If that's true, can you provide some details about that?

2021-05-05 15:27 UTC, atatmaja commented
Where could I find info about how the ETL is run on our prod machine?

2021-05-05 15:28 UTC, atatmaja approved these changes
Thanks for writing this up! Please see comments

2021-05-05 15:34 UTC, atatmaja requested changes
sorry meant to request changes

2021-05-05 15:41 UTC, simonarocco requested changes
can you add documentation please for how one would go about setting up access to the staging and dev machines? everything from the credentials we would need to what commands we would run to ssh into the machine. and then also commands for how to navigate the machines once we are in. e.g. where would we find the logs for the etl and the backend app? where would we find the scripts that deal with automatic deployment and automatically running the etl? maybe don't put some of the sensitive info in the readme but somewhere

2021-05-18 03:12 UTC, simonarocco approved these changes
lgtm, just add the extra things that we discussed on sunday

2021-05-20 21:31 UTC, atatmaja approved these changes

2021-06-16 02:35 UTC, merged